myprofile_app/urls.py
from django.urls import path
from .views import(create_recipe, 
                    read_one_recipe, delete_recipe, 
                    update_recipe, my_profile, category_recipes
                )

urlpatterns = [
    path('create_recipe/', create_recipe, name='create_recipe'),
    path('read_one_recipe/<int:pk>/', read_one_recipe, name='read_one_recipe'),
    path('delete_recipe/<int:id>/', delete_recipe, name='delete_recipe'),
    path('update_recipe/<int:id>/', update_recipe, name='update_recipe'),
    path('category_recipes/<int:pk>', category_recipes, name='category_recipes'),
    path('my_profile', my_profile, name='my_profile'),
]

user_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import Register

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', Register.as_view(), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

web_culinary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import list_category
# from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', list_category, name="home"),
    path('user/', include('user_app.urls')),
    path('myprofile/', include('myprofile_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

myprofile_app/models.py
from django.db import models
from user_app.models import UserAuth


class Category(models.Model):
    name_category = models.CharField(max_length=50)

class Recipe(models.Model):
    img_recipe = models.ImageField(upload_to='img_recipe')
    name_recipe = models.CharField(max_length=50)
    description = models.TextField()
    ingredients = models.TextField()
    cooking_process = models.TextField()
    date_add = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(UserAuth, on_delete=models.CASCADE)

user_app/models.py
from django.db import models


from django.contrib.auth.models import AbstractUser

class UserAuth(AbstractUser):
    city = models.CharField(max_length=50)

myprofile_app/forms.py
from django import forms
from django.db.models.base import Model
from .models import Category, Recipe


class MyChoiceCategory(forms.ModelChoiceField):
    def label_from_instance(self, obj: Model) -> str:
        return super().label_from_instance(obj.name_category)

class FormRecipe(forms.ModelForm):
    category = MyChoiceCategory(queryset=Category.objects.all(), empty_label=None)

    class Meta:
        model = Recipe
        exclude = ['user']
        widgets = {
            'name_recipe': forms.Textarea,
            'description': forms.Textarea, 
            'ingredients': forms.Textarea,
        }

class FormRecipeUpdate(forms.ModelForm):

    category = MyChoiceCategory(queryset=Category.objects.all())
    class Meta:
        model = Recipe
        exclude = ['user']
        widgets = {
            'name_recipe': forms.Textarea,
            'description': forms.Textarea, 
            'ingredients': forms.Textarea,
        }

myprofile_app/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Recipe, Category
from .forms import FormRecipe, FormRecipeUpdate 
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required 
from django.core.paginator import Paginator


@login_required
def create_recipe(request):
    if request.method == 'POST':
        form = FormRecipe(request.POST or None, request.FILES)
        if form.is_valid():
            img_recipe = form.cleaned_data['img_recipe']
            name_recipe = form.cleaned_data['name_recipe']
            description = form.cleaned_data['description']
            ingredients = form.cleaned_data['ingredients']
            cooking_process = form.cleaned_data['cooking_process']
            category = form.cleaned_data['category']

            fs = FileSystemStorage()
            filename = fs.save(img_recipe.name, img_recipe)
            recipe = Recipe(img_recipe = filename,
                            name_recipe = name_recipe,
                            description = description,
                            ingredients = ingredients,
                            cooking_process = cooking_process,
                            user = request.user,
                            category = category)
            recipe.save()
            return redirect ('my_profile')
    else:
        form = FormRecipe()
    return render (request, 'myprofile/create_recipe.html', {'form': form})

def category_recipes(request, pk):
    category_list = Category.objects.all()
    category = Category.objects.get(pk=pk)
    recipes = Recipe.objects.filter(category = pk)
    current_page = Paginator(recipes, 4)
    page_number = request.GET.get("page")
    page_obj = current_page.get_page(page_number)
    context = {
            'recipes': recipes, 
            'category_list': category_list,
            'category': category,
            "page_obj": page_obj,
    }
    return render (request, 'maincontent/category_recipes.html', context)

def read_one_recipe(request, pk):
    recipe = get_object_or_404(Recipe, pk = int(pk))
    return render (request, 'myprofile/read_one_recipe.html', {'recipe': recipe})

def my_profile(request):
    user = request.user
    recipe_all = Recipe.objects.filter(user = user)
    current_page = Paginator(recipe_all, 4)
    page_number = request.GET.get("page")
    page_obj = current_page.get_page(page_number)
    context = {
                'user': user, 
                'recipe_all': recipe_all, 
                "page_obj": page_obj
    }
    return render (request, 'myprofile/my_profile.html', context)

def delete_recipe(request, id):
    recipe = get_object_or_404(Recipe, pk = id)
    if recipe is not None:
        recipe.delete()
    return redirect ('my_profile')

def update_recipe(request, id):
    get_recipe = get_object_or_404(Recipe, pk=id)
    if request.method == 'POST':
        form = FormRecipeUpdate(request.POST or None, request.FILES, instance=get_recipe)
        if form.is_valid():
            form.save()
            return redirect ('my_profile')
    else:
        form = FormRecipeUpdate(instance=get_recipe)
    return render (request, 'myprofile/update_recipe.html', {'form': form})

user_app/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django.views import View
from .froms import UserCreationForm

class Register(View):
    template_name = 'registration/register.html'
    template_home = 'home.html'

    def get(self, request):
        context = {
            'form': UserCreationForm()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password) # автоматич авторизация
            login(request, user)
            return render(request, self.template_home)
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

web_culinary/views.py
from django.shortcuts import render
from myprofile_app.models import Category, Recipe


def list_category(request):
    for_recipe =  Recipe.objects.order_by('?')[:4]
    category_list = Category.objects.all()
    return render (request, 'home.html', {'for_recipe': for_recipe, 'category_list': category_list})

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block main__title %}
    <title>base_templates</title>
    {% endblock %}
    
    {% load static %}
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}"  rel="stylesheet" >
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</head>
<body>

  <nav class="navbar navbar-expand-lg d-flex justify-content-between" style="background-color: rgba(88, 202, 243, 0.76);" max-width="600px">
    <div class="container">
      <div class="navbar-collapse">
          <nav class="navbar navbar-light">
              <a class="navbar-brand" href="{% url 'home' %}">
                  <img src="{% static 'image/main_icon.png' %}" alt="logo" width="40" height="34">
                  <b>CHIEFFF COOK</b>
              </a>
          </nav>
        {% block category %}
        {% endblock %}
      </div>
      <div class="navbar">
            {% if user.is_authenticated %}
            <nav class="navbar">
              <form action="{% url 'my_profile' %}" class="inline">
                <button class="btn btn-outline-success me-2" type="button ">Мой профиль</button>
              </form>
              <form action="{% url 'logout' %}" class="inline">
                <button class="btn btn-outline-success me-2" type="button ">Выход</button>
              </form>
            </nav>
            {% else %}
            <nav class="navbar">
              <form action="{% url 'register' %}" class="inline">
                <button class="btn btn-outline-success me-2" type="button ">Регистрация</button>
              </form>
              <form action="{% url 'login' %}" class="inline">
                <button class="btn btn-outline-success me-2" type="button ">Авторизация</button>
              </form>
            </nav>
            {% endif %}
      </div>
    </div>
  </nav>
  {% block title %}
  {% endblock %}

  {% block subtitle %}
  {% endblock %}

  {% block content %}
  {% endblock %}

  <div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
          <img src="{% static 'image/main_icon.png' %}" alt="" width="24" height="24">
        </a>
        <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2023 Company, Inc</span>
      </div>
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="text-body-secondary" href="https://ya.ru/"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
        <li class="ms-3"><a class="text-body-secondary" href="https://ya.ru/"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
        <li class="ms-3"><a class="text-body-secondary" href="https://ya.ru/"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
      </ul>
    </footer>
  </div>

  <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="facebook" viewBox="0 0 16 16">
      <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
    </symbol>
    <symbol id="instagram" viewBox="0 0 16 16">
        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
    </symbol>
    <symbol id="twitter" viewBox="0 0 16 16">
      <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
    </symbol>
  </svg>
</body>
</html>

templates/home.html
{% extends 'base.html'%}

{% block main__title %}
<title>Домашняя страница</title>
{% endblock %}

{% block category %}
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle me-2" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Категории рецептов
    </button>
    <ul class="dropdown-menu">
      {% for category in category_list %}
        <li><a class="dropdown-item" href="{% url 'category_recipes' category.pk %}">{{ category.name_category }}</a></li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}


{% block title %}
  <center>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          {% if user.is_authenticated %}
            <p><h5 class="fw-light"><b>Здраствуйте {{ user }}</h5></p>
          {% endif %}
          <h1 class="fw-light"><b>Сборник рецептов</b></h1>
          <b></b><h1 class="fw-light"><b>CHIEFFF COOK</b></h1></b>
          <p class="lead text-muted">В данном сборнике рецептов, представлены ваши самые любимые блюда, которыми вы готовы поделиться с CHIEFFF COOK, 
          а он опубликует ваши рецепты на своём сайте, что бы каждый мог научиться так же вкусно готовить как и вы!</p>
        </div>
      </div>
    </section>
  </center>
{% endblock %}


{% block subtitle %}
  <section class="text-center container">
    <h1 class="fw-light">Ниже представлены 4 случайных блюда<br>из книги рецептов CHIEFFF COOK</h1>
    <h1>
      {% for category in list_category %}
        {{ category }}
      {% endfor %}
    </h1>
      <a href="{% url 'home' %}" class="btn btn-primary my-2">Обновить рецепты</a>
  </section>
{% endblock %}


{% block content %}
{% for item in for_recipe %}
<center>
  <div class="album py-5 bg-light" style="max-width: 600px;">
    <div class="container">
      <div class="row align-items-center">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ item.img_recipe.url }}" alt="img_recipe">
            <div class="card-body">
              <b><p class="card-text">{{ item.name_recipe|linebreaks }}</p></b>
              <p class="card-text">{{ item.description|linebreaks }}</p>
              <div>
                <form action="{% url 'read_one_recipe' item.pk %}" class="inline">
                  <button type="button " class="btn btn-sm btn-outline-secondary">Посмотреть рецепт</button>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</center>
{% endfor %}
{% endblock %}

templates/maincontent/category_recipes.html
{% extends 'base.html'%}

{% block main__title %}
<title>Кастегория рецептов</title>
{% endblock %}

{% block category %}
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle me-2" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Категории рецептов
  </button>
  <ul class="dropdown-menu">
    {% for category in category_list %}
      <li><a class="dropdown-item" href="{% url 'category_recipes' category.pk %}">{{ category.name_category }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}


{% block title %}
<center>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light"><b>Вашему вниманию представлены рецепты категории</b></h1>
        <b></b><h1 class="fw-light"><b><u>{{ category.name_category }}</u></b></h1></b>
      </div>
    </div>
  </section>
</center>
{% endblock %}

{% block subtitle %}
{% endblock %}

{% block content %}
{% for item in page_obj %}
<center>
  <div class="album py-5 bg-light" style="max-width: 600px;">
    <div class="container">
      <div class="row align-items-center">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ item.img_recipe.url }}" alt="img_recipe">
            <div class="card-body">
              <b><p class="card-text">{{ item.name_recipe|linebreaks }}</p></b>
              <p class="card-text">{{ item.description|linebreaks }}</p>
              <div>
                <div class="btn-group">
                  <center>
                    <form action="{% url 'read_one_recipe' item.pk %}" class="inline">
                      <button type="button " class="btn btn-sm btn-outline-secondary">Посмотреть рецепт</button>
                    </form>
                </center>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</center>
<hr>
{% endfor %}
<center>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page=1/">&laquo; Первая</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
    {% endif %}
    </li>
    {% for page in page_obj.paginator.page_range %}
      {% if page == page_obj.number %}
        <li class="page-item active"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
      {% else %}
        <li><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
    </li>
    <li class="page-item"></li>
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
    </li>
    {% endif %}
  </ul>
  </span>
</center>


{% endblock %}

templates/myprofile/create_recipe.html
{% extends 'base.html'%}

{% block main__title %}
    <title>Создание рецепта</title>
{% endblock %}

{% block category %}
{% endblock %}

{% block title %}
    <center>
        <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
            <b></b><h2 class="fw-light"><b>Заполните необходимые поля для добавления рецепта</b></h2></b>
            </div>
        </div>
        <hr>
        </section>
    </center>
{% endblock %}

{% block content %}
    <center>
        <form method="post" enctype="multipart/form-data">
            <table>
                {% csrf_token %}
                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="formFile" class="form-label">Выберите картинку</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.img_recipe }}
                        </td>
                    </tr>
                </div>
                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="exampleFormControlTextarea1" class="form-label">Название блюда</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.name_recipe }}
                        </td>
                    </tr>
                </div>

                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="exampleFormControlTextarea1" class="form-label">Описание блюда</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.description }}>
                        </td>
                    </tr>
                </div>

                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="exampleFormControlTextarea1" class="form-label">Ингридиенты</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.ingredients }}
                        </td>
                    </tr>
                </div>

                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="exampleFormControlTextarea1" class="form-label">Процесс приготовления</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.cooking_process }}
                        </td>
                    </tr>
                </div>

                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="id_category" class="form-label">Выберите Категорию</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.category }}
                        </td>
                    </tr>
                </div>


            </table>
                <hr>
                <button type="submit" class="btn btn-success">
                    Сохранить рецепт и вернуться в свой профиль
                </button>

        </form>
    </center>
{% endblock %}

templates/myprofile/read_one_recipe.html
{% extends 'base.html'%}

{% block main__title %}
<title>Рецепт</title>
{% endblock %}

{% block category %}
{% endblock %}

{% block title %}
  <center>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light"><b>Вашему вниманию представлен рецепт блюда</b></h1>
          <h2 class="fw-light">{{ recipe.name_recipe|linebreaks }}</h1>
          <h2 class="fw-light">приготовленный поваром "{{ recipe.user }}"</h1>
          
        </div>
      </div>
    </section>
  </center>
{% endblock %}

{% block subtitle %}

<center>
    <div class="album py-5 bg-light" style="max-width: 600px;">
      <div class="container">
        <div class="row align-items-center">
          <div class="col">
            <div class="card shadow-sm">
              <img src="{{ recipe.img_recipe.url }}" alt="img_recipe">
              <div class="card-body">
                <b><p class="card-text">Категория блюда:</p></b>
                <p class="card-text">{{ recipe.category.name_category|linebreaks }}</p>
                <b><p class="card-text">Описание блюда:</p></b>
                <p class="card-text">{{ recipe.description|linebreaks }}</p>
                <b><p class="card-text">Ингридиенты:</p></b>
                <p class="card-text">{{ recipe.ingredients|linebreaks }}</p>
                <b><p class="card-text">Ход приготовления</p></b>
                <p class="card-text">{{ recipe.cooking_process|linebreaks }}</p>
                <div>
                  <form action="{% url 'home' %}" class="inline">
                    <button type="button " class="btn btn-sm btn-outline-secondary">Вернуться на главную</button>
                  </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </center>
{% endblock %}

templates/myprofile/update_recipe.html
{% extends 'base.html'%}

{% block main__title %}
<title>Создание рецепта</title>
{% endblock %}

{% block category %}
{% endblock %}


{% block title %}
  <center>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <b></b><h2 class="fw-light"><b>Измените необходимые поля выбранного рецепта</b></h2></b>
        </div>
      </div>
      <hr>
    </section>
  </center>
{% endblock %}

{% block content %}
<center>
    <form method="post" enctype="multipart/form-data">
        <table>
            {% csrf_token %}
            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="formFile" class="form-label">Выберите картинку</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.img_recipe }}
                    </td>
                </tr>
            </div>
            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="exampleFormControlTextarea1" class="form-label">Название блюда</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.name_recipe }}
                    </td>
                </tr>
            </div>

            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="exampleFormControlTextarea1" class="form-label">Описание блюда</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.description }}>
                    </td>
                </tr>
            </div>

            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="exampleFormControlTextarea1" class="form-label">Ингридиенты</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.ingredients }}
                    </td>
                </tr>
            </div>

            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="exampleFormControlTextarea1" class="form-label">Процесс приготовления</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.cooking_process }}
                    </td>
                </tr>
            </div>

            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="id_category" class="form-label">Выберите Категорию</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.category }}
                    </td>
                </tr>
            </div>


        </table>
            <hr>
            <button type="submit" class="btn btn-success">
                Сохранить рецепт и вернуться в свой профиль
            </button>

    </form>
</center>


{% endblock %}